name: QistX Windows CI

on:
  push:
    branches:
      - zulqurnain/auth_features
  pull_request:
    branches:
      - zulqurnain/auth_features

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file from Secrets
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          # Agar aur bhi variables hain toh wo yahan add kar dein
        shell: bash

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Flutter code
        run: flutter analyze || true  # Pipeline fail hone se bachane ke liye

      - name: Run automated tests
        run: flutter test

      - name: Build Windows application
        run: flutter build windows --release