name: QistX Windows CI

on:
  push:
    branches:
      - zulqurnain/auth_features
  pull_request:
    branches:
      - zulqurnain/auth_features

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create .env file from Secrets
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_PUBLISHABLE_KEY=${{ secrets.SUPABASE_PUBLISHABLE_KEY }}" >> .env
          echo "WEB_CLIENT=${{ secrets.WEB_CLIENT }}" >> .env
        shell: bash

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze Flutter code
        run: flutter analyze || true

      - name: Run automated tests
        run: flutter test

      - name: Build Windows application
        run: flutter build windows --release

      - name: Copy .env file to Release folder
        run: |
          mkdir -p build/windows/x64/runner/Release/
          cp .env build/windows/x64/runner/Release/
        shell: bash

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QistX-Windows-Release
          path: build/windows/x64/runner/Release/